name: audio_monitor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  background_fetch: ^1.2.1
  change_app_package_name: ^1.1.0
  device_imei: ^0.0.4+1
  device_info: ^2.0.3
  device_uuid: ^0.0.4
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_acrcloud:
    path: ./flutter_acrcloud/
  flutter_foreground_task: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_redux: ^0.10.0
  http: ^0.13.6
  intl: ^0.18.1
  permission_handler: ^11.0.1
  redux: ^5.0.0
  shared_preferences: ^2.2.2
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/FuturaBookfont.ttf
          weight: 400
        - asset: assets/fonts/futuramediumbt.ttf
          weight: 500
        - asset: assets/fonts/futur.ttf
          weight: 700
        - asset: assets/fonts/FuturaExtraBlackfont.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
